### PR TITLE
Fix support for Pathnames in options broken by 8ce400715ce

### PR DESCRIPTION
**Pull request by jrafanie**

### CODE REVIEW

**Comment by jrafanie** [comment]
@Fryguy @kbrock fixes 

```
     NoMethodError:
       undefined method `empty?' for #<Pathname:script.rb>
     # ./lib/awesome_spawn/command_line_builder.rb:86:in `sanitize_key'
     # ./lib/awesome_spawn/command_line_builder.rb:80:in `sanitize_key_values'
     # ./lib/awesome_spawn/command_line_builder.rb:75:in `sanitize_item'
     # ./lib/awesome_spawn/command_line_builder.rb:67:in `block in sanitize_associative_array'
```

**Comment by kbrock** [comment]
Good fix.

Do you prefer `to_s` or maybe just check that it implements `empty?` with a `kind_of?` or `responds_to?` instead?

**Comment by jrafanie** [comment]
In this one case, I think it makes sense to do to_s because the guard clause is returning early if it's an empty string.. 

Note, I think symbols were also going throw this error. I can add a test case for symbols to prevent a regression if it makes sense.

**Comment by kbrock** [comment]
(I was just trying to avoid the string conversion)

This looks good :shipit:

**Comment by jrafanie** [comment]
@Fryguy @bdunne @kbrock Are you ok with merging this?
